server:
  port: 8087

spring:
  datasource:
    database: POSTGRESQL
    platform: postgres
    url: jdbc:postgresql://localhost:5432/skillbasetest
    username: user
    password: 12345

  data:
    mongodb:
      host: localhost
      port: 27017
      database: skillsTest

  jpa:
    hibernate:
      ddl-auto: create-drop